using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CodeChecker
{
    public class Operation
    {
        public string Text { get; set; }
        public string Text2 { get; set; }

        public Dictionary<string, string> AllFiles = new Dictionary<string, string>();

        public List<string> FoundMatches = new List<string>();
        public string docPath = Environment.GetFolderPath(Environment.SpecialFolder.Desktop);


        public void ExtractFilePaths()
        { //files and their contents added to the dictionary
          // Dictionary<string, string> AllFiles = new Dictionary<string, string>();
            var files = Directory.EnumerateFiles(docPath, "*.cs", SearchOption.AllDirectories);

            foreach (var f in files)
            {
                //filter the folders from the path
                if (!f.Contains("Debug") && !f.Contains(".vs") && !f.Contains("packages") && !f.Contains("obj") &&
                    !f.Contains("Properties") && !f.Contains("Resources") && !f.Contains("Program.cs"))
                {
                    string text = File.ReadAllText(f).ToLower();

                    //filter the file content
                    if (!string.IsNullOrEmpty(text) && !text.Contains("<auto-generated>"))
                    {
                        AllFiles.Add(f, text);
                    }
                }
            }

        }


    }
}
